SARA:
    # Publish all joint states -----------------------------------
    joint_state_controller:
        type: joint_state_controller/JointStateController
        publish_rate: 100  

    # Position Controllers ---------------------------------------
    joint_controller:
        type: effort_controllers/JointTrajectoryController
        joints: 
            - joint0
            - joint1
            - joint2
            - joint3
            - joint4
            - joint5
            - joint6
            - joint7

        gains: 
            joint0: {p: 100.0, i: 0.1, d: 0.1}
            joint1: {p: 100.0, i: 0.1, d: 0.1}
            joint2: {p: 100.0, i: 0.1, d: 0.1}
            joint3: {p: 100.0, i: 0.1, d: 0.1}
            joint4: {p: 100.0, i: 0.1, d: 0.1}
            joint5: {p: 100.0, i: 0.1, d: 0.1} 
            joint6: {p: 100.0, i: 0.1, d: 0.1}
            joint7: {p: 100.0, i: 0.1, d: 0.1}