controller_list:
  - name: fake_REACH_controller
    joints:
      - chair_joint1
      - chair_joint2
      - joint0
      - joint1
      - joint2
      - joint3
      - joint4
      - joint5
      - joint6
      - joint7
      - joint8
      - joint9
      - joint10
      - joint11
      - joint12
      - joint13
      - joint14
      - joint15