<?xml version="1.0" ?>
<robot name="SARA" xmlns:xacro="http://www.ros.org/wiki/xacro">

	<link name="base_link"/>
	<joint name="set_worldaxis" type="fixed">
		<origin rpy="1.570796326795 0 0" xyz="0.0 0.0 0.0"/>
		<parent link="base_link"/>
		<child link="chair_base"/>
		<axis xyz="0 0 0"/>
		<limit effort="0" lower="-1" upper="1" velocity="0"/>
	</joint>
	<link name="chair_base">
		<inertial>
			<origin rpy="0.0 0.0 0.0" xyz="0.0 0.0 0.0"/>
			<mass value="0"/>
			<inertia ixx="0" ixy="0" ixz="0" iyy="0" iyz="0" izz="0"/>
		</inertial>
		<visual>
			<origin rpy="0.0 0.0 0.0" xyz="0.0 0.0 0.0"/>
			<geometry>
				<mesh filename="package://wheelchair/meshes/base.stl"/>
			</geometry>
			<material name="">
				<color rgba="0.792156862745098 0.819607843137255 0.933333333333333 1"/>
			</material>
		</visual>
		<collision>
			<origin rpy="0.0 0.0 0.0" xyz="0.0 0.0 0.0"/>
			<geometry>
				<mesh filename="package://wheelchair/meshes/base.stl"/>
			</geometry>
		</collision>
	</link>
	<link name="chair_link1">
		<inertial>
			<origin rpy="0.0 0.0 0.0" xyz="0.0 0.0 0.0"/>
			<mass value="0"/>
			<inertia ixx="0" ixy="0" ixz="0" iyy="0" iyz="0" izz="0"/>
		</inertial>
		<visual>
			<origin rpy="0.0 0.0 0.0" xyz="0.0 0.0 0.0"/>
			<geometry>
				<mesh filename="package://wheelchair/meshes/link1.stl"/>
			</geometry>
			<material name="">
				<color rgba="0.792156862745098 0.819607843137255 0.933333333333333 1"/>
			</material>
		</visual>
		<collision>
			<origin rpy="0.0 0.0 0.0" xyz="0.0 0.0 0.0"/>
			<geometry>
				<mesh filename="package://wheelchair/meshes/link1.stl"/>
			</geometry>
		</collision>
	</link>
	<link name="chair_link2">
		<inertial>
			<origin rpy="0.0 0.0 0.0" xyz="0.0 0.0 0.0"/>
			<mass value="0"/>
			<inertia ixx="0" ixy="0" ixz="0" iyy="0" iyz="0" izz="0"/>
		</inertial>
		<visual>
			<origin rpy="0.0 0.0 0.0" xyz="0.0 0.0 0.0"/>
			<geometry>
				<mesh filename="package://wheelchair/meshes/link2.stl"/>
			</geometry>
			<material name="">
				<color rgba="0.792156862745098 0.819607843137255 0.933333333333333 1"/>
			</material>
		</visual>
		<collision>
			<origin rpy="0.0 0.0 0.0" xyz="0.0 0.0 0.0"/>
			<geometry>
				<mesh filename="package://wheelchair/meshes/link2.stl"/>
			</geometry>
		</collision>
	</link>
	<joint name="chair_joint1" type="continuous">
		<origin rpy="0.0 0.0 0.0" xyz="0.6162001603339797 0.9987983990460869 -0.10515639316991093"/>
		<parent link="chair_base"/>
		<child link="chair_link1"/>
		<axis xyz="-0.9698848187392894 0.24356401227352137 0.00010151002393613432"/>
		<limit effort="0" lower="-1" upper="1" velocity="0"/>
	</joint>
	<joint name="chair_joint2" type="continuous">
		<origin rpy="0.0 0.0 0.0" xyz="-0.05333534440670149 0.013396020675043162 0.07950558261589771"/>
		<parent link="chair_link1"/>
		<child link="chair_link2"/>
		<axis xyz="-0.00010466193655742605 -1.1955594058051162e-14 -0.99999999452302"/>
		<limit effort="0" lower="-1" upper="1" velocity="0"/>
	</joint>





<!-- ***************** -->
<!-- Manipulator stuff -->
<!-- ***************** -->


<!-- "xacro inorder SARA.xacro > SARA.urdf" -->

<xacro:macro name="simple_link" params="link_name stl_name">
    <!-- ${link_name} -->
    <!--*********************************************************************************-->
    <link name="${link_name}">
        <inertial>
            <origin rpy="0.0 0.0 0.0" xyz="0.0 0.0 0.0"/>
            <mass value="0.2"/>
            <inertia ixx="0.01" ixy="0.01" ixz="0.01" iyy="0.01" iyz="0.01" izz="0.01"/>
        </inertial>

        <visual>
            <origin rpy="0.0 0.0 0.0" xyz="0.0 0.0 0.0"/>
            <geometry>
                <mesh filename="package://wheelchair/meshes/${stl_name}.stl"/>
            </geometry>
            <material name="">
                <color rgba="0.792156862745098 0.819607843137255 0.933333333333333 1"/>
            </material>
        </visual>

        <collision>
            <origin rpy="0.0 0.0 0.0" xyz="0.0 0.0 0.0"/>
            <geometry>
                <mesh filename="package://wheelchair/meshes/${stl_name}.stl"/>
            </geometry>
        </collision>
    </link>

    <!-- Slow down gazebo sim to prevent erratic behaviour (https://answers.ros.org/question/43429/making-revolute-joint-stay-at-rest-if-no-effortwrench-is-applied/)-->
    <gazebo reference="${link_name}">
        <dampingFactor>0.005</dampingFactor>
    </gazebo>


    <!--*********************************************************************************-->
</xacro:macro>



<xacro:macro name="segment_joints" params="joint_num parent_link child_link *origin *axis">
    <!-- joint${joint_num#} -->
    <!--*********************************************************************************-->
	<joint name="joint${joint_num#}" type="revolute">
		<parent link="${parent_link}"/>
		<child link="${child_link}"/>
        <xacro:insert_block name="origin"/>
        <xacro:insert_block name="axis"/>
		<limit effort="30" lower="-0.7853981633974483" upper="0.7853981633974483" velocity="1.0"/>
        <dynamics damping="0.0" friction="0.0"/>
	</joint>

    <transmission name="tran${joint_num#}">
		<type>transmission_interface/SimpleTransmission</type>
		<joint name="joint${joint_num#}">
			<hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
		</joint>
		<actuator name="motor${joint_num#}">
			<hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
            <mechanicalReduction>1</mechanicalReduction>
		</actuator>
	</transmission>

    <!--*********************************************************************************-->
</xacro:macro>



<xacro:macro name="rigid_link" params="joint1 joint2 link1 link2 link3">
<!--*********************************************************************************-->
	<!-- Rigid link block -->
	<joint name="${joint1}" type="fixed">
	<origin rpy="0 0 0" xyz="0.0 0.0768 -0.02"/>
		<parent link="${link1}"/>
		<child link="${link2}"/>
	</joint>

	<joint name="${joint2}" type="fixed">
	<origin rpy="0 0 0" xyz="${joint_0_x-0.07} ${joint_0_y+0.013} ${joint_0_z-0.023}"/>
		<parent link="${link2}"/>
		<child link="${link3}"/>
	</joint>
	<!--*********************************************************************************-->
</xacro:macro>


<xacro:property name="joint_0_x" value="0.04316036512320408" />
<xacro:property name="joint_0_y" value="0.04848245206563817" />
<xacro:property name="joint_0_z" value="0.027454509104734993" />

<xacro:property name="joint_1_x" value="-0.016550000000000054" />
<xacro:property name="joint_1_y" value="0.040054000000004225" />
<xacro:property name="joint_1_z" value="-0.01210000000000057" />


<!-- First segment -->
    <xacro:simple_link link_name="link0a" stl_name="rigid_link"/>
	<xacro:simple_link link_name="link0b" stl_name="segment_base"/>
    <xacro:simple_link link_name="link1" stl_name="segment_link1"/>
    <xacro:simple_link link_name="link2" stl_name="segment_link2"/>

	<!-- First rigid link joints -->
	<joint name="segment_base" type="fixed">
	<origin rpy="0 0 1.348574" xyz="-0.1218 0.03 -0.11"/>
		<parent link="chair_link2"/>
		<child link="link0a"/>
	</joint>

	<joint name="jointb" type="fixed">
	<origin rpy="0 0 0" xyz="${joint_0_x-0.07} ${joint_0_y+0.013} ${joint_0_z-0.023}"/>
		<parent link="link0a"/>
		<child link="link0b"/>
	</joint>


	<!-- segment joints -->

    <xacro:segment_joints joint_num="0" parent_link="link0b" child_link="link1">
        <origin rpy="0.0 0.0 0.0" xyz="${joint_0_x} ${joint_0_y} ${joint_0_z}"/>
        <axis xyz="-1.0 0.0 0.0"/>
    </xacro:segment_joints>
    <xacro:segment_joints joint_num="1" parent_link="link1" child_link="link2">
        <origin rpy="0.0 0.0 0.0" xyz="${joint_1_x} ${joint_1_y} ${joint_1_z}"/>
        <axis xyz="0.0 0.0 1.0"/>
    </xacro:segment_joints>



<!-- Second segment (test) -->
    <xacro:simple_link link_name="link3" stl_name="segment_base"/>
    <xacro:simple_link link_name="link4" stl_name="segment_link1"/>
    <xacro:simple_link link_name="link5" stl_name="segment_link2"/>


	<joint name="second_segment_base" type="fixed">
	    <origin rpy="0 0 0" xyz="-0.02661 ${joint_1_y-0.0145-0.005} -0.0153545"/>
		<parent link="link2"/>
		<child link="link3"/>
	</joint>
    <xacro:segment_joints joint_num="2" parent_link="link3" child_link="link4">
        <origin rpy="0.0 0.0 0.0" xyz="${joint_0_x} ${joint_0_y} ${joint_0_z}"/>
        <axis xyz="-1.0 0.0 0.0"/>
    </xacro:segment_joints>
    <xacro:segment_joints joint_num="3" parent_link="link4" child_link="link5">
        <origin rpy="0.0 0.0 0.0" xyz="${joint_1_x} ${joint_1_y} ${joint_1_z}"/>
        <axis xyz="0.0 0.0 1.0"/>
    </xacro:segment_joints>


<!-- Third segment (test) -->

	<!-- Segment #3 rigid link joints -->

    <xacro:simple_link link_name="link6a" stl_name="rigid_link"/>
	<xacro:simple_link link_name="link6b" stl_name="segment_base"/>
    <xacro:simple_link link_name="link7" stl_name="segment_link1"/>
    <xacro:simple_link link_name="link8" stl_name="segment_link2"/>

	<!-- Segment #3 rigid link joints -->

	<xacro:rigid_link joint1="jointc" joint2="jointd" link1="link5" link2="link6a" link3="link6b"/>

	<!-- Segmen #3 joints -->

    <xacro:segment_joints joint_num="4" parent_link="link6b" child_link="link7">
        <origin rpy="0.0 0.0 0.0" xyz="${joint_0_x} ${joint_0_y} ${joint_0_z}"/>
        <axis xyz="-1.0 0.0 0.0"/>
    </xacro:segment_joints>
    <xacro:segment_joints joint_num="5" parent_link="link7" child_link="link8">
        <origin rpy="0.0 0.0 0.0" xyz="${joint_1_x} ${joint_1_y} ${joint_1_z}"/>
        <axis xyz="0.0 0.0 1.0"/>
    </xacro:segment_joints>


<!-- Fourth segment (test) -->

	<xacro:simple_link link_name="link9" stl_name="segment_base"/>
    <xacro:simple_link link_name="link10" stl_name="segment_link1"/>
    <xacro:simple_link link_name="link11" stl_name="segment_link2"/>


	<joint name="third_segment_base" type="fixed">
	    <origin rpy="0 0 0" xyz="-0.02661 ${joint_1_y-0.0145-0.005} -0.0153545"/>
		<parent link="link8"/>
		<child link="link9"/>
	</joint>

    <xacro:segment_joints joint_num="6" parent_link="link9" child_link="link10">
        <origin rpy="0.0 0.0 0.0" xyz="${joint_0_x} ${joint_0_y} ${joint_0_z}"/>
        <axis xyz="-1.0 0.0 0.0"/>
    </xacro:segment_joints>
    <xacro:segment_joints joint_num="7" parent_link="link10" child_link="link11">
        <origin rpy="0.0 0.0 0.0" xyz="${joint_1_x} ${joint_1_y} ${joint_1_z}"/>
        <axis xyz="0.0 0.0 1.0"/>
    </xacro:segment_joints>

<!-- Fifth segment (test) -->

    <xacro:simple_link link_name="link12" stl_name="segment_base"/>
    <xacro:simple_link link_name="link13" stl_name="segment_link1"/>
    <xacro:simple_link link_name="link14" stl_name="segment_link2"/>
	

	<joint name="fifth_segment_base" type="fixed">
	    <origin rpy="0 0 0" xyz="-0.02661 ${joint_1_y-0.0145-0.005} -0.0153545"/>
		<parent link="link11"/>
		<child link="link12"/>
	</joint>
    <xacro:segment_joints joint_num="8" parent_link="link12" child_link="link13">
        <origin rpy="0.0 0.0 0.0" xyz="${joint_0_x} ${joint_0_y} ${joint_0_z}"/>
        <axis xyz="-1.0 0.0 0.0"/>
    </xacro:segment_joints>
    <xacro:segment_joints joint_num="9" parent_link="link13" child_link="link14">
        <origin rpy="0.0 0.0 0.0" xyz="${joint_1_x} ${joint_1_y} ${joint_1_z}"/>
        <axis xyz="0.0 0.0 1.0"/>
    </xacro:segment_joints>


	<!-- 
		 Gazebo plugins: 

			ros_control
			* Accepts new desired trajectories via follow_joint_trajectory, while joint_state_publisher publishes joint_states.
			* Makes joints move.

			joint_state_publisher
			* Publish current state of each joint to a topic 
	-->
	<gazebo>

		<plugin name="control" filename="libgazebo_ros_control.so" >
			<robotNamespace>/SARA</robotNamespace>
		</plugin>

		<plugin name="joint_state_publisher" filename="libgazebo_ros_joint_state_publisher.so" >
			<jointName>joint0, joint1, joint2, joint3, joint4, joint5, joint6, joint7</jointName>
			<updateRate>100.0</updateRate>
			<alwaysOn>true</alwaysOn>
			<!-- <robotNamespace>/SARA</robotNamespace> -->
		</plugin>

	</gazebo>









</robot>

