<?xml version="1.0" ?>
<robot name="SARA" xmlns:xacro="http://www.ros.org/wiki/xacro">

<!-- "xacro inorder SARA.xacro > SARA.urdf" -->

<xacro:macro name="simple_link" params="link_name stl_name">
    <!-- ${link_name} -->
    <!--*********************************************************************************-->
    <link name="${link_name}">
        <inertial>
            <origin rpy="0.0 0.0 0.0" xyz="0.0 0.0 0.0"/>
            <mass value="1.0"/>
            <inertia ixx="0.04" ixy="0.04" ixz="0.04" iyy="0.04" iyz="0.04" izz="0.04"/>
        </inertial>

        <visual>
            <origin rpy="0.0 0.0 0.0" xyz="0.0 0.0 0.0"/>
            <geometry>
                <mesh filename="package://sara_8dof_v1/meshes/${stl_name}.stl"/>
            </geometry>
            <material name="">
                <color rgba="0.792156862745098 0.819607843137255 0.933333333333333 1"/>
            </material>
        </visual>

        <collision>
            <origin rpy="0.0 0.0 0.0" xyz="0.0 0.0 0.0"/>
            <geometry>
                <mesh filename="package://sara_8dof_v1/meshes/${stl_name}.stl"/>
            </geometry>
        </collision>
    </link>
    <!--*********************************************************************************-->
</xacro:macro>



<xacro:macro name="segment_joints" params="joint_num parent_link child_link *origin *axis">
    <!-- joint${joint_num#} -->
    <!--*********************************************************************************-->
	<joint name="joint${joint_num#}" type="revolute">
		<parent link="${parent_link}"/>
		<child link="${child_link}"/>
        <xacro:insert_block name="origin"/>
        <xacro:insert_block name="axis"/>
		<limit effort="30" lower="-0.7853981633974483" upper="0.7853981633974483" velocity="1.0"/>
        <dynamics damping="0.0" friction="0.0"/>
	</joint>

    <transmission name="tran${joint_num#}">
		<type>transmission_interface/SimpleTransmission</type>
		<joint name="joint${joint_num#}">
			<hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
		</joint>
		<actuator name="motor${joint_num#}">
			<hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
            <mechanicalReduction>1</mechanicalReduction>
		</actuator>
	</transmission>

    <!--*********************************************************************************-->
</xacro:macro>


<xacro:property name="joint_0_x" value="0.04316036512320408" />
<xacro:property name="joint_0_y" value="0.04848245206563817" />
<xacro:property name="joint_0_z" value="0.027454509104734993" />

<xacro:property name="joint_1_x" value="-0.016550000000000054" />
<xacro:property name="joint_1_y" value="0.040054000000004225" />
<xacro:property name="joint_1_z" value="-0.01210000000000057" />


<!-- First segment -->
	<link name="world"/>
    <xacro:simple_link link_name="base_link" stl_name="base_link"/>
    <xacro:simple_link link_name="link1" stl_name="link1"/>
    <xacro:simple_link link_name="link2" stl_name="link2"/>


	<joint name="world_frame" type="fixed">
	<origin rpy="1.57079632679 0 0" xyz="0.0 0.0 0.01"/>
		<parent link="world"/>
		<child link="base_link"/>
	</joint>
    <xacro:segment_joints joint_num="0" parent_link="base_link" child_link="link1">
        <origin rpy="0.0 0.0 0.0" xyz="${joint_0_x} ${joint_0_y} ${joint_0_z}"/>
        <axis xyz="-1.0 0.0 0.0"/>
    </xacro:segment_joints>
    <xacro:segment_joints joint_num="1" parent_link="link1" child_link="link2">
        <origin rpy="0.0 0.0 0.0" xyz="${joint_1_x} ${joint_1_y} ${joint_1_z}"/>
        <axis xyz="0.0 0.0 1.0"/>
    </xacro:segment_joints>



<!-- Second segment (test) -->
    <xacro:simple_link link_name="link3" stl_name="base_link"/>
    <xacro:simple_link link_name="link4" stl_name="link1"/>
    <xacro:simple_link link_name="link5" stl_name="link2"/>


	<joint name="second_segment_base" type="fixed">
	    <origin rpy="0 0 0" xyz="-0.02661 ${joint_1_y-0.0145} -0.0153545"/>
		<parent link="link2"/>
		<child link="link3"/>
	</joint>
    <xacro:segment_joints joint_num="2" parent_link="link3" child_link="link4">
        <origin rpy="0.0 0.0 0.0" xyz="${joint_0_x} ${joint_0_y} ${joint_0_z}"/>
        <axis xyz="-1.0 0.0 0.0"/>
    </xacro:segment_joints>
    <xacro:segment_joints joint_num="3" parent_link="link4" child_link="link5">
        <origin rpy="0.0 0.0 0.0" xyz="${joint_1_x} ${joint_1_y} ${joint_1_z}"/>
        <axis xyz="0.0 0.0 1.0"/>
    </xacro:segment_joints>


<!-- Third segment (test) -->
    <xacro:simple_link link_name="link6" stl_name="base_link"/>
    <xacro:simple_link link_name="link7" stl_name="link1"/>
    <xacro:simple_link link_name="link8" stl_name="link2"/>


	<joint name="third_segment_base" type="fixed">
	    <origin rpy="0 0 0" xyz="-0.02661 ${joint_1_y-0.0145} -0.0153545"/>
		<parent link="link5"/>
		<child link="link6"/>
	</joint>
    <xacro:segment_joints joint_num="4" parent_link="link6" child_link="link7">
        <origin rpy="0.0 0.0 0.0" xyz="${joint_0_x} ${joint_0_y} ${joint_0_z}"/>
        <axis xyz="-1.0 0.0 0.0"/>
    </xacro:segment_joints>
    <xacro:segment_joints joint_num="5" parent_link="link7" child_link="link8">
        <origin rpy="0.0 0.0 0.0" xyz="${joint_1_x} ${joint_1_y} ${joint_1_z}"/>
        <axis xyz="0.0 0.0 1.0"/>
    </xacro:segment_joints>


<!-- Fourth segment (test) -->
    <xacro:simple_link link_name="link9" stl_name="base_link"/>
    <xacro:simple_link link_name="link10" stl_name="link1"/>
    <xacro:simple_link link_name="link11" stl_name="link2"/>


	<joint name="fourth_segment_base" type="fixed">
	    <origin rpy="0 0 0" xyz="-0.02661 ${joint_1_y-0.0145} -0.0153545"/>
		<parent link="link8"/>
		<child link="link9"/>
	</joint>
    <xacro:segment_joints joint_num="6" parent_link="link9" child_link="link10">
        <origin rpy="0.0 0.0 0.0" xyz="${joint_0_x} ${joint_0_y} ${joint_0_z}"/>
        <axis xyz="-1.0 0.0 0.0"/>
    </xacro:segment_joints>
    <xacro:segment_joints joint_num="7" parent_link="link10" child_link="link11">
        <origin rpy="0.0 0.0 0.0" xyz="${joint_1_x} ${joint_1_y} ${joint_1_z}"/>
        <axis xyz="0.0 0.0 1.0"/>
    </xacro:segment_joints>


	<!-- 
		 Gazebo plugins: 

			ros_control
			* Accepts new desired trajectories via follow_joint_trajectory, while joint_state_publisher publishes joint_states.
			* Makes joints move.

			joint_state_publisher
			* Publish current state of each joint to a topic 
	-->
	<gazebo>

		<plugin name="control" filename="libgazebo_ros_control.so" >
			<robotNamespace>/SARA</robotNamespace>
		</plugin>

		<plugin name="joint_state_publisher" filename="libgazebo_ros_joint_state_publisher.so" >
			<jointName>joint0, joint1, joint2, joint3, joint4, joint5, joint6, joint7</jointName>
			<updateRate>100.0</updateRate>
			<alwaysOn>true</alwaysOn>
			<!-- <robotNamespace>/SARA</robotNamespace> -->
		</plugin>

	</gazebo>

</robot>