SARA:
    # Publish all joint states -----------------------------------
    joint_state_controller:
        type: joint_state_controller/JointStateController
        publish_rate: 100  

    # Position Controllers ---------------------------------------
    joint_controller:
        type: effort_controllers/JointTrajectoryController
        joints: 
            - joint0
            - joint1
        gains: 
            joint0: {p: 100.0, i: 0.1, d: 10.0}
            joint1: {p: 100.0, i: 0.1, d: 10.0}
            
