SARA:
    # Publish all joint states -----------------------------------
    joint_state_controller:
        type: joint_state_controller/JointStateController
        publish_rate: 100  

    # Position Controllers ---------------------------------------
    joint0_controller:
        type: effort_controllers/JointPositionController
        joint: joint0
        actuator: motor0
        pid: {p: 100.0, i: 0.1, d: 10.0}

    joint1_controller:
        type: effort_controllers/JointPositionController
        joint: joint1
        actuator: motor1
        pid: {p: 100.0, i: 0.1, d: 10.0}