# Telling MoveIt! where to find follow_joint_trajectory action server being provided by ros_control plugin,
# and which joints are to be controlled.
controller_list:
  - name: SARA/joint_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - joint0
      - joint1