REACH:
    # Publish all joint states -----------------------------------
    joint_state_controller:
        type: joint_state_controller/JointStateController
        publish_rate: 100  

    # Position Controllers ---------------------------------------
    joint_controller:
        type: effort_controllers/JointTrajectoryController
        joints: 
            - chair_joint1
            - chair_joint2
            - joint0
            - joint1
            - joint2
            - joint3
            - joint4
            - joint5
            - joint6
            - joint7
            - joint8
            - joint9
            - joint10
            - joint11
            - joint12
            - joint13
            - joint14
            - joint15


        gains: 
            chair_joint1: {p: 100.0, i: 0.1, d: 0.1}
            chair_joint2: {p: 100.0, i: 0.1, d: 0.1}
            joint0: {p: 100.0, i: 0.1, d: 0.1}
            joint1: {p: 100.0, i: 0.1, d: 0.1}
            joint2: {p: 100.0, i: 0.1, d: 0.1}
            joint3: {p: 100.0, i: 0.1, d: 0.1}
            joint4: {p: 100.0, i: 0.1, d: 0.1}
            joint5: {p: 100.0, i: 0.1, d: 0.1} 
            joint6: {p: 100.0, i: 0.1, d: 0.1}
            joint7: {p: 100.0, i: 0.1, d: 0.1}
            joint8: {p: 100.0, i: 0.1, d: 0.1}
            joint9: {p: 100.0, i: 0.1, d: 0.1}
            joint10: {p: 100.0, i: 0.1, d: 0.1}
            joint11: {p: 100.0, i: 0.1, d: 0.1}
            joint12: {p: 100.0, i: 0.1, d: 0.1}
            joint13: {p: 100.0, i: 0.1, d: 0.1} 
            joint14: {p: 100.0, i: 0.1, d: 0.1}
            joint15: {p: 100.0, i: 0.1, d: 0.1}

